config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects do
    resources :pledges
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pledge.rb
class Pledge < ApplicationRecord
  belongs_to :project

  AMOUNT_LEVELS = [25, 50, 100, 200, 500]

  validates :name, presence: true
  validates :email, format: { with: /(\S+)@(\S+)/ }
  validates :amount, inclusion: { in: AMOUNT_LEVELS }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :pledges, dependent: :destroy 
  
  validates :name, :description, presence: true
  validates :description, length: { maximum: 500 }
  validates :target_pledge_amount, numericality: { greater_than: 0 }
  validates :website, format: {
    with:     /https?:\/\/[\S]+/,
    message:  "must have a valid url"
  }
  validates :image_file_name, allow_blank: true, format: {
    with:    /\w+\.(gif|jpg|jpeg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  def pledging_expired?
    pledging_ends_on < Time.now
  end

  def total_amount_pledged
    pledges.sum(:amount)
  end

  def amount_outstanding
    target_pledge_amount - total_amount_pledged
  end

  def funded?
    amount_outstanding <= 0
  end

  def self.ongoing
    where("pledging_ends_on > ?", Time.now).order("target_pledge_amount desc")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :set_project

  def index
    @pledges = @project.pledges
  end

  def new
    @pledge = @project.pledges.new
  end

  def create
    @pledge = @project.pledges.new(pledge_params)
    if @pledge.save 
      redirect_to project_pledges_path(@project), notice: "Thanks for pledging!"
    else
      render :new
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def pledge_params
    params.require(:pledge).permit(:name, :email, :comment, :amount)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.ongoing
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, notice: "Project successfully updated!"
    else
      render :edit
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: "Project successfully created!"
    else
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, alert: "Project successfully deleted!"
  end

  private

  def project_params
    params.require(:project)
      .permit(:name, :description, :target_pledge_amount, :pledging_ends_on, :website, :image_file_name, :team_members)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
  def pledge_link(project)
    if project.funded?
      content_tag(:strong, "Funded!")
    else
      amount_left = number_to_currency(project.amount_outstanding)

      div = content_tag :div, class: 'pledge-cta-wrapper' do
        concat(content_tag(:p, "Only #{amount_left} left!"))
        concat(link_to 'Pledge!', new_project_pledge_path(project), class: 'pledge-cta')       
      end

      return div
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def format_date(project)
    if project.pledging_expired?
      content_tag(:strong, "All Done!")
    else
      "#{distance_of_time_in_words_to_now(project.pledging_ends_on)} remaining"
    end
  end

  def image_for(project)
    if project.image_file_name.blank?
      asset_path 'placeholder.png'
    else
      asset_path project.image_file_name
    end
  end
end

app/views/layouts/_flashes.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <p>
    Copyright &copy; 2016
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="app-header">
  <h1>FUNdit</h1>
  <div id="toggle-dots" class="button_container">
    <span class="top"></span>
    <span class="top2"></span>
    <span class="middle"></span>
    <span class="bottom"></span>
    <span class="bottom2"></span>
  </div>
  <div id="overlay" class="overlay">
    <div class="overlay-menu">
      <ul>
        <li>Sign In</li>
        <li>Sign Up</li>
      </ul>
    </div>
  </div>  
</header>

app/views/layouts/_sidebar.html.erb
<aside class="sidebar">
  <nav>
   <ul>
     <li>
       <%= link_to 'All Projects', projects_path %>
     </li>
     <li>
       <%= link_to 'Add New Project', new_project_path %>
     </li>
   </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FUNdit</title>
    <%= csrf_meta_tags %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= render "layouts/header" %>

      <% if content_for?(:hero) %>
        <%= yield :hero %>
      <% end %>

      <%= render "layouts/flashes" %>

        <section id="<%= @main_container_id ||'content' %>">
          <%= yield %>
          <%= render "layouts/sidebar" %>
        </section>

      <%= render "layouts/footer" %>
    </main>
  </body>
</html>

app/views/pledges/index.html.erb
<h1 class="pledges-header">Pledges for <%= link_to(@project.name, @project) %></h2>

<% if @project.pledges.length == 0 %>
  <p class="no-pledges">There are no pledges for this project.</p>
<% else %>
  <ol class="all-pledges-list">
    <% @pledges.each do |pledge| %>
      <li>
        <div class="pledge-list-item">
           <p>
            <strong><%= number_to_currency(pledge.amount) %></strong>
            by <%= pledge.name %>
          </p>
          <p>email: <strong><%= pledge.email %></strong></p>
          <p class="pledged-time"><%= time_ago_in_words(pledge.created_at) %> ago</p>  

          <% if pledge.comment.length > 0 %>
            <p>&quot;<%= pledge.comment %>&quot;</p>
          <% end %>  

          <%= pledge_link(@project) %>   
        </div>
      </li>
    <% end %>
  </ol>
<% end %>

app/views/pledges/new.html.erb
<h1 class="form-title">New Pledge for <%#= link_to @pledge.name, project_pledge_path(@pledge) %></h1>

<%= form_for [@project, @pledge], :html => {:class => 'form'} do |f| %>
  <%= render "shared/errors", object: @pledge %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>         
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>         
        <%= f.text_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :amount %>
        <%= f.select :amount, Pledge::AMOUNT_LEVELS, prompt: "Pick one" %>   
      </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "Leave an optional comment" %>
      </li>
    </ol>
    <div class="form-buttons">
      <%= f.submit 'Create Pledge' %> 
      <%= link_to "Cancel", @project %>
    </div>
  </fieldset>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:class => 'form'}) do |f| %>
  <%= render 'shared/errors', object: @project %>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :target_pledge_amount %>
  <%= f.number_field :target_pledge_amount %>

  <%= f.label :pledging_ends_on %>
  <%= f.date_select :pledging_ends_on %>

  <%= f.label :website %>
  <%= f.text_field :website %>

  <%= f.label :team_members %>
  <%= f.text_field :team_members %>

  <%= f.label :image_file_name %>
  <%= f.text_field :image_file_name %>

  <div class="form-buttons">
    <%= f.submit %>
    <%= link_to "Cancel", projects_path %>    
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1 class="form-title"><%= @project.name %></h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<% @main_container_id = 'index_page' %>

<% content_for :hero do %>
  <section class="hero">
    <h2>Give a bit.<br/><br/>Change a&nbsp;lot</h2>
  </section>
<% end %>

<h3 class="projects-header"><%= pluralize(@projects.size, 'Project') %></h3>

<section class="all-projects">
  <% @projects.each do |project| %>
    <%= link_to(project, class: 'project-section-link') do %>
      <div class="project-wrapper">
        <header style="background-image: url(<%= image_for(project) %>)">
          <div class="project-title">
            <h3><%= project.name %></h3>
          </div>
        </header>
        <p class="project-description">&mdash; <%= truncate(project.description, length: 150, separator: ' ') %></p>
        <p class="learn-more">Learn more</p>
      </div>
    <% end %>
  <% end %>
</section>

app/views/projects/new.html.erb
<h1 class="form-title">Add New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<header class="single-project-header" style="background-image: url(<%= image_for(@project) %>)">
  <h2><%= @project.name %></h2>
</header>
<section class="single-project-description-wrapper">
  <p class="single-project-description"><%= @project.description %></p>
  <p>
    <strong>Target pledge amount: </strong>
    <%= number_to_currency(@project.target_pledge_amount) %>
  </p>
  <p>
    <strong>Pledging ends on: </strong>
    <span class="ending-date"><%= format_date(@project) %></span>
  </p>
  <p>
    <strong>Website: </strong>
    <%= link_to(@project.website, @project.website, class: 'project-website') %>
  </p>
  <p>
    <strong>Team members: </strong>
    <%= @project.team_members %>
  </p>
  <p class="pledges-amount">
    <%= link_to pluralize(@project.pledges.size, "pledge"), 
                  project_pledges_path(@project) %>
  </p>
  <%= pledge_link(@project) %>
  <nav class="bottom-links">
    <%= link_to "All projects", projects_path %>
    <%= link_to "Edit", edit_project_path(@project) %>
    <%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?" } %> 
  </nav>    
</section>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>